kind: pipeline
name: default

steps:

- name: test
  image: golang:1.22.2
  volumes:
  - name: deps
    path: /go
  commands:
  - go test ./... -cover -coverprofile coverage.out
  when:
    event:
      exclude:
      - tag

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token:
      from_secret: CODECOV_TOKEN
  when:
    event:
      exclude:
      - tag


- name: build and push the service
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kgantsov/limiter
    context: .
    dockerfile: ./Dockerfile
    auto_tag: true
  environment:
    DOCKER_BUILDKIT: 1

- name: publish
  image: plugins/github-release
  volumes:
  - name: deps
    path: /go
  settings:
    api_key:
      from_secret: github_token
    files: dist/*
  when:
    event:
      - tag

volumes:
- name: deps
  temp: {}
